### PR TITLE
Use `rdma-core` package (instead of CDT) & add to `linux_aarch64`

### PR DESCRIPTION
**Pull request by jakirkham**
Part of issue: https://github.com/conda-forge/cuda-feedstock/issues/28

Previously we used the CDT for `rdma-core`. However it would be better to use the package. Especially so as this CDT is not provided on AlmaLinux 8. This makes that change. It is also aligned with how we use `rdma-core` elsewhere.

Additionally it looks like `rdma-core` would be needed on `linux_aarch64`, but we didn't have it there before. So this makes sure to add it.

<hr>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Not seeing Azure here. Going to try restarting

@conda-forge-admin , please restart CI

**Comment by jakirkham** [comment]
Looks like that fixed it

**Comment by jakirkham** [comment]
Am seeing the following [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=894525&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=622 )

```
sed: can't read /home/conda/feedstock_root/build_artifacts/libcufile_1710268372716/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/pkgconfig/cufile*.pc: No such file or directory
```

Based on looking locally, this appears to be happening because `${PREFIX}/lib/pkgconfig` already exists. So the line below moves `pkg-config` into `${PREFIX}/lib/pkgconfig`, which gives us `${PREFIX}/lib/pkgconfig/pkg-config`. Where instead we would want all the `.pc` files in `${PREFIX}/lib/pkgconfig`

https://github.com/conda-forge/libcufile-feedstock/blob/7f8e1ec3054c062a85da3279bb9f85e54c1f5087/recipe/build.sh#L10

IOW this looks like a bug in `build.sh`

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please lint

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by adibbley** [comment]
I'm not sure the `rdma-core` package is providing what we needed from the cdt package originally.

One example from the 12.4.1 build log I see:
```
INFO (libcufile,targets/x86_64-linux/lib/libcufile_rdma.so.1.9.1): Needed DSO x86_64-conda-linux-gnu/sysroot/usr/lib64/libmlx5.so.1 found in CDT/compiler package conda-forge/noarch::libibverbs-cos7-x86_64==22.4=h9b0a68f_1105
```
And here I see:
```
WARNING (libcufile,targets/x86_64-linux/lib/libcufile_rdma.so.1.9.1): $RPATH/libmlx5.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
```

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by leofang** [comment]
It seems the rerendering failed 😅

**Comment by jakirkham** [comment]
Not sure why it wouldn't find the libraries, they are all there

```
rdma-core-52.0-hcccb83c_0/lib
├── libefa.so -> libefa.so.1.3.52.0
├── libefa.so.1 -> libefa.so.1.3.52.0
├── libefa.so.1.3.52.0
├── libhns.so -> libhns.so.1.0.52.0
├── libhns.so.1 -> libhns.so.1.0.52.0
├── libhns.so.1.0.52.0
├── libibmad.so -> libibmad.so.5.3.52.0
├── libibmad.so.5 -> libibmad.so.5.3.52.0
├── libibmad.so.5.3.52.0
├── libibnetdisc.so -> libibnetdisc.so.5.1.52.0
├── libibnetdisc.so.5 -> libibnetdisc.so.5.1.52.0
├── libibnetdisc.so.5.1.52.0
├── libibumad.so -> libibumad.so.3.2.52.0
├── libibumad.so.3 -> libibumad.so.3.2.52.0
├── libibumad.so.3.2.52.0
├── libibverbs.so -> libibverbs.so.1.14.52.0
├── libibverbs.so.1 -> libibverbs.so.1.14.52.0
├── libibverbs.so.1.14.52.0
├── libmana.so -> libmana.so.1.0.52.0
├── libmana.so.1 -> libmana.so.1.0.52.0
├── libmana.so.1.0.52.0
├── libmlx4.so -> libmlx4.so.1.0.52.0
├── libmlx4.so.1 -> libmlx4.so.1.0.52.0
├── libmlx4.so.1.0.52.0
├── libmlx5.so -> libmlx5.so.1.24.52.0
├── libmlx5.so.1 -> libmlx5.so.1.24.52.0
├── libmlx5.so.1.24.52.0
├── librdmacm.so -> librdmacm.so.1.3.52.0
├── librdmacm.so.1 -> librdmacm.so.1.3.52.0
└── librdmacm.so.1.3.52.0
```

**Comment by leofang** [comment]
I seem to recall we encountered a similar situation elsewhere (but can't find the example now), where a CTK component in `$PREFIX/targets/<arch>/lib` depends on non-CTK packages in `$PREFIX/lib`. Maybe we need to patch rpath manually for the cuFILE libraries?

**Comment by jakirkham** [comment]
Looks like we need `libnuma` based on [this CI warning]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=990954&view=logs&j=6494c7a6-a019-59a3-6f3d-9bab8ca96717&t=18c91bca-a25a-5f89-34d4-93bbec4021bc&l=996 ):

```
WARNING (gds-tools,gds/tools/gdsio): $RPATH/libnuma.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
```

**Comment by jakirkham** [comment]
Yeah it looks like there is something up with the `rpath` for `gds-tools` based on [this line from CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=990954&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=861 ):

```
WARNING (gds-tools,gds/tools/gdsio): $RPATH/libcufile.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.
```

**Comment by jakirkham** [comment]
Yep, this is related to issue: https://github.com/conda-forge/cuda-feedstock/issues/10

**Comment by jakirkham** [comment]
@conda-forge-admin , please restart CI

**Comment by billysuh7** [comment]
@conda-forge-admin, please restart ci

**Review by billysuh7 — APPROVED** [review]
Sorry I forgot @h-vetinari to approve this. LGTM.

**Comment by jakirkham** [comment]
Thanks Billy! 🙏

Were you meaning PR: https://github.com/conda-forge/cuda-nvcc-impl-feedstock/pull/25 ?

**Comment by billysuh7** [comment]
> Thanks Billy! 🙏
> 
> Were you meaning PR: [conda-forge/cuda-nvcc-impl-feedstock#25](https://github.com/conda-forge/cuda-nvcc-impl-feedstock/pull/25) ?

That is all set also, I approved it and put more comment. Thanks.

**Comment by jakirkham** [comment]
Thanks Billy! 🙏

**Comment by jakirkham** [comment]
The conclusion Billy and I reached after looking into the warnings above more closely is there is likely a remaining RPATH issue in this package, which we will need to look into. This will be follow up work

**Pull request merged**
